"""Emit the Python representation of the M3 metamodel from a :class:`MetaModel`.

Each Pure metaclass becomes a ``@dataclass(kw_only=True)`` whose bases mirror
the Pure generalizations and whose fields mirror the declared properties.
``kw_only`` sidesteps the ordering rules that multiple inheritance + defaults
would otherwise violate. Enumerations become ``enum.Enum`` classes; primitive
types and packageable multiplicities become module-level singletons.
"""

from __future__ import annotations

import keyword
import re

from .schema import MetaClass, MetaModel, MetaProperty, TypeRef

_PRIMITIVE_PY: dict[str, str] = {
    "String": "str",
    "Boolean": "bool",
    "Integer": "int",
    "Float": "float",
    "Number": "float",
    "Decimal": "decimal.Decimal",
    "Byte": "int",
    "Date": "datetime.date",
    "StrictDate": "datetime.date",
    "LatestDate": "datetime.date",
    "DateTime": "datetime.datetime",
    "StrictTime": "datetime.time",
}

_HEADER = '''\
# Generated by pure_python.codegen from vendor/legend-pure/m3.pure -- do not edit.
#
# This is the Pure M3 core type system expressed as Python: every metaclass
# (Class, Property, Type, GenericType, Multiplicity, ...) is a dataclass whose
# fields and base classes are taken directly from the Pure metamodel.
from __future__ import annotations

import datetime
import decimal
import enum
import typing
from dataclasses import dataclass, field

'''


def _py_name(model: MetaModel, name: str | None, is_type_parameter: bool) -> str:
    if is_type_parameter:
        return name if name in model.type_parameter_names else "typing.Any"
    if name is None:
        return "typing.Any"
    if name in _PRIMITIVE_PY:
        return _PRIMITIVE_PY[name]
    return name  # a metaclass or enumeration -- emitted with this exact name


def _render_typeref(model: MetaModel, ref: TypeRef) -> str:
    base = _py_name(model, ref.name, ref.is_type_parameter)
    if ref.arguments:
        return f"{base}[{', '.join(_render_typeref(model, a) for a in ref.arguments)}]"
    return base


def _py_base_type(model: MetaModel, prop: MetaProperty) -> str:
    base = _py_name(model, prop.type_name, prop.is_type_parameter)
    if prop.type_arguments:
        return f"{base}[{', '.join(_render_typeref(model, a) for a in prop.type_arguments)}]"
    return base


def _annotation(model: MetaModel, prop: MetaProperty) -> str:
    base = _py_base_type(model, prop)
    if prop.upper is None or prop.upper > 1:
        return f"list[{base}]"
    if prop.lower >= 1:
        return base
    return f"{base} | None"


def _field_line(model: MetaModel, prop: MetaProperty) -> str:
    annotation = _annotation(model, prop)
    name = prop.name + ("_" if keyword.iskeyword(prop.name) else "")
    if prop.upper is None or prop.upper > 1:
        return f"    {name}: {annotation} = field(default_factory=list)"
    if prop.lower >= 1:
        return f"    {name}: {annotation}"
    return f"    {name}: {annotation} = None"


def _topo_sorted(model: MetaModel) -> list[MetaClass]:
    """Bases before subclasses, otherwise preserving m3.pure declaration order."""
    ordered: list[MetaClass] = []
    visiting: set[str] = set()
    done: set[str] = set()

    def visit(name: str) -> None:
        if name in done or name not in model.classes:
            return
        if name in visiting:
            raise ValueError(f"generalization cycle through {name}")
        visiting.add(name)
        for base in model.classes[name].bases:
            visit(base)
        visiting.discard(name)
        done.add(name)
        ordered.append(model.classes[name])

    for name in model.classes:
        visit(name)
    return ordered


def _emit_enum_member(name: str) -> str:
    ident = re.sub(r"\W", "_", name)
    if not ident or ident[0].isdigit():
        ident = "_" + ident
    if keyword.iskeyword(ident) or ident in ("None", "True", "False"):
        ident += "_"
    return ident


def _emit_class(model: MetaModel, cls: MetaClass) -> str:
    base_list = list(cls.bases)
    if cls.type_parameters:
        base_list.append(f"typing.Generic[{', '.join(cls.type_parameters)}]")
    bases = f"({', '.join(base_list)})" if base_list else ""
    lines = ["@dataclass(kw_only=True)", f"class {cls.name}{bases}:"]
    seen: set[str] = set()
    body: list[str] = []
    for prop in cls.properties:
        if prop.name in seen:
            continue
        seen.add(prop.name)
        body.append(_field_line(model, prop))
    if not body:
        body.append("    pass")
    lines.extend(body)
    return "\n".join(lines)


def _emit_multiplicity(name: str, lower: int, upper: int | None) -> str:
    lo = f"MultiplicityValue(value={lower})"
    parts = [f'name="{name}"', f"lowerBound={lo}"]
    if upper is not None:
        parts.append(f"upperBound=MultiplicityValue(value={upper})")
    return f"{name} = PackageableMultiplicity({', '.join(parts)})"


def emit_module(model: MetaModel) -> str:
    out: list[str] = [_HEADER]

    out.append("# --- Enumerations " + "-" * 56)
    for enum_def in model.enums.values():
        out.append(f"class {enum_def.name}(enum.Enum):")
        if enum_def.values:
            for v in enum_def.values:
                out.append(f'    {_emit_enum_member(v)} = "{v}"')
        else:
            out.append("    pass")
        out.append("")

    type_params = sorted(model.type_parameter_names)
    if type_params:
        out.append("# --- Type parameters " + "-" * 53)
        for name in type_params:
            out.append(f'{name} = typing.TypeVar("{name}")')
        out.append("")

    out.append("# --- Metaclasses " + "-" * 57)
    for cls in _topo_sorted(model):
        out.append(_emit_class(model, cls))
        out.append("")

    out.append("# --- Primitive types " + "-" * 53)
    for prim in model.primitives.values():
        out.append(f'{prim.name} = PrimitiveType(name="{prim.name}")')
    out.append("")

    out.append("# --- Packageable multiplicities " + "-" * 42)
    for mult in model.multiplicities.values():
        out.append(_emit_multiplicity(mult.name, mult.lower, mult.upper))
    out.append("")

    all_names = (
        list(model.enums)
        + [c.name for c in model.classes.values()]
        + list(model.primitives)
        + list(model.multiplicities)
    )
    out.append("__all__ = [")
    for name in all_names:
        out.append(f'    "{name}",')
    out.append("]")
    out.append("")
    return "\n".join(out)
