# Generated by pure_python.codegen from vendor/legend-pure/m3.pure -- do not edit.
#
# This is the Pure M3 core type system expressed as Python: every metaclass
# (Class, Property, Type, GenericType, Multiplicity, ...) is a dataclass whose
# fields and base classes are taken directly from the Pure metamodel.
from __future__ import annotations

import datetime
import decimal
import enum
import typing
from dataclasses import dataclass, field


# --- Enumerations --------------------------------------------------------
class AggregationKind(enum.Enum):
    None_ = "None"
    Shared = "Shared"
    Composite = "Composite"

class GenericTypeOperationType(enum.Enum):
    Union = "Union"
    Difference = "Difference"
    Subset = "Subset"
    Equal = "Equal"

# --- Metaclasses ---------------------------------------------------------
@dataclass(kw_only=True)
class Any:
    classifierGenericType: GenericType | None = None
    elementOverride: ElementOverride | None = None

@dataclass(kw_only=True)
class Type(Any):
    name: str | None = None
    generalizations: list[Generalization] = field(default_factory=list)
    specializations: list[Generalization] = field(default_factory=list)

@dataclass(kw_only=True)
class ElementWithStereotypes(Any):
    stereotypes: list[Stereotype] = field(default_factory=list)

@dataclass(kw_only=True)
class ElementWithTaggedValues(Any):
    taggedValues: list[TaggedValue] = field(default_factory=list)

@dataclass(kw_only=True)
class AnnotatedElement(ElementWithStereotypes, ElementWithTaggedValues):
    pass

@dataclass(kw_only=True)
class ModelElement(AnnotatedElement):
    name: str | None = None

@dataclass(kw_only=True)
class Referenceable(Any):
    referenceUsages: list[ReferenceUsage] = field(default_factory=list)

@dataclass(kw_only=True)
class PackageableElement(ModelElement, Referenceable):
    package: Package | None = None

@dataclass(kw_only=True)
class PropertyOwner(PackageableElement):
    pass

@dataclass(kw_only=True)
class ElementWithConstraints(Any):
    constraints: list[Constraint] = field(default_factory=list)

@dataclass(kw_only=True)
class Testable(Any):
    tests: list[Test] = field(default_factory=list)

@dataclass(kw_only=True)
class Class(Type, PropertyOwner, ElementWithConstraints, PackageableElement, Testable):
    properties: list[Property] = field(default_factory=list)
    originalMilestonedProperties: list[Property] = field(default_factory=list)
    propertiesFromAssociations: list[Property] = field(default_factory=list)
    qualifiedProperties: list[QualifiedProperty] = field(default_factory=list)
    qualifiedPropertiesFromAssociations: list[QualifiedProperty] = field(default_factory=list)
    typeParameters: list[TypeParameter] = field(default_factory=list)
    typeVariables: list[VariableExpression] = field(default_factory=list)
    multiplicityParameters: list[InstanceValue] = field(default_factory=list)

@dataclass(kw_only=True)
class TypeParameter(Any):
    name: str
    contravariant: bool | None = None
    lowerBound: GenericType | None = None
    upperBound: GenericType | None = None

@dataclass(kw_only=True)
class GenericType(Referenceable):
    rawType: Type | None = None
    typeParameter: TypeParameter | None = None
    typeVariableValues: list[ValueSpecification] = field(default_factory=list)
    typeArguments: list[GenericType] = field(default_factory=list)
    multiplicityArguments: list[Multiplicity] = field(default_factory=list)

@dataclass(kw_only=True)
class InferredGenericType(GenericType):
    pass

@dataclass(kw_only=True)
class ReferenceUsage(Any):
    owner: Any
    propertyName: str
    offset: int

@dataclass(kw_only=True)
class DataType(Type):
    pass

@dataclass(kw_only=True)
class Measure(DataType, PackageableElement):
    canonicalUnit: Unit | None = None
    nonCanonicalUnits: list[Unit] = field(default_factory=list)

@dataclass(kw_only=True)
class PrimitiveType(DataType, PackageableElement, ElementWithConstraints):
    extended: bool | None = None
    typeVariables: list[VariableExpression] = field(default_factory=list)

@dataclass(kw_only=True)
class Unit(DataType, Referenceable):
    measure: Measure
    conversionFunction: FunctionDefinition | None = None

@dataclass(kw_only=True)
class Enumeration(DataType, PackageableElement):
    values: list[typing.Any] = field(default_factory=list)

@dataclass(kw_only=True)
class Enum(AnnotatedElement):
    name: str

@dataclass(kw_only=True)
class Nil(Any):
    pass

@dataclass(kw_only=True)
class ElementOverride(Any):
    pass

@dataclass(kw_only=True)
class GetterOverride(ElementOverride):
    getterOverrideToOne: Function | None = None
    getterOverrideToMany: Function | None = None
    hiddenPayload: Any | None = None

@dataclass(kw_only=True)
class ConstraintsOverride(ElementOverride):
    constraintsManager: Function | None = None

@dataclass(kw_only=True)
class ConstraintsGetterOverride(GetterOverride, ConstraintsOverride):
    pass

@dataclass(kw_only=True)
class Multiplicity(Any):
    lowerBound: MultiplicityValue | None = None
    upperBound: MultiplicityValue | None = None
    multiplicityParameter: str | None = None

@dataclass(kw_only=True)
class MultiplicityValue(Any):
    value: int | None = None

@dataclass(kw_only=True)
class PackageableMultiplicity(Multiplicity, PackageableElement):
    pass

@dataclass(kw_only=True)
class Generalization(Any):
    specific: Type
    general: GenericType

@dataclass(kw_only=True)
class Function(Referenceable):
    name: str | None = None
    functionName: str | None = None
    applications: list[FunctionExpression] = field(default_factory=list)

@dataclass(kw_only=True)
class AbstractProperty(Function, ModelElement):
    genericType: GenericType
    multiplicity: Multiplicity
    owner: PropertyOwner

@dataclass(kw_only=True)
class Property(AbstractProperty):
    aggregation: AggregationKind
    defaultValue: DefaultValue | None = None

@dataclass(kw_only=True)
class Package(PackageableElement):
    children: list[PackageableElement] = field(default_factory=list)

@dataclass(kw_only=True)
class ImportGroup(PackageableElement):
    imports: list[Import] = field(default_factory=list)

@dataclass(kw_only=True)
class Import(Any):
    path: str

@dataclass(kw_only=True)
class ValueSpecification(Any):
    genericType: GenericType
    multiplicity: Multiplicity
    usageContext: ValueSpecificationContext | None = None

@dataclass(kw_only=True)
class Expression(ValueSpecification):
    pass

@dataclass(kw_only=True)
class NonExecutableValueSpecification(ValueSpecification):
    values: list[Any] = field(default_factory=list)

@dataclass(kw_only=True)
class VariableExpression(Expression):
    name: str
    functionTypeOwner: FunctionType | None = None

@dataclass(kw_only=True)
class InstanceValue(ValueSpecification):
    values: list[Any] = field(default_factory=list)

@dataclass(kw_only=True)
class ValueSpecificationContext(Any):
    offset: int

@dataclass(kw_only=True)
class ExpressionSequenceValueSpecificationContext(ValueSpecificationContext):
    functionDefinition: FunctionDefinition

@dataclass(kw_only=True)
class InstanceValueSpecificationContext(ValueSpecificationContext):
    instanceValue: InstanceValue

@dataclass(kw_only=True)
class ClassConstraintValueSpecificationContext(ValueSpecificationContext):
    type: Type

@dataclass(kw_only=True)
class ParameterValueSpecificationContext(ValueSpecificationContext):
    functionExpression: FunctionExpression

@dataclass(kw_only=True)
class KeyValueValueSpecificationContext(ValueSpecificationContext):
    functionExpression: FunctionExpression

@dataclass(kw_only=True)
class FunctionExpression(Expression):
    func: Function
    importGroup: ImportGroup
    parametersValues: list[ValueSpecification] = field(default_factory=list)
    functionName: str | None = None
    propertyName: InstanceValue | None = None
    qualifiedPropertyName: InstanceValue | None = None
    originalMilestonedProperty: Function | None = None
    originalMilestonedPropertyParametersValues: list[ValueSpecification] = field(default_factory=list)
    resolvedTypeParameters: list[GenericType] = field(default_factory=list)
    resolvedMultiplicityParameters: list[Multiplicity] = field(default_factory=list)

@dataclass(kw_only=True)
class SimpleFunctionExpression(FunctionExpression):
    pass

@dataclass(kw_only=True)
class PackageableFunction(PackageableElement, Function):
    preConstraints: list[Constraint] = field(default_factory=list)
    postConstraints: list[Constraint] = field(default_factory=list)

@dataclass(kw_only=True)
class FunctionDefinition(Function):
    expressionSequence: list[ValueSpecification] = field(default_factory=list)

@dataclass(kw_only=True)
class NativeFunction(PackageableFunction):
    pass

@dataclass(kw_only=True)
class FunctionType(Type, Referenceable):
    function: list[Function] = field(default_factory=list)
    parameters: list[VariableExpression] = field(default_factory=list)
    returnType: GenericType
    returnMultiplicity: Multiplicity
    typeParameters: list[TypeParameter] = field(default_factory=list)
    multiplicityParameters: list[InstanceValue] = field(default_factory=list)

@dataclass(kw_only=True)
class QualifiedProperty(AbstractProperty, FunctionDefinition):
    id: str

@dataclass(kw_only=True)
class ConcreteFunctionDefinition(FunctionDefinition, PackageableFunction, Testable):
    pass

@dataclass(kw_only=True)
class LambdaFunction(FunctionDefinition):
    openVariables: list[str] = field(default_factory=list)

@dataclass(kw_only=True)
class ImportStub(Any):
    importGroup: ImportGroup
    idOrPath: str
    resolvedNode: Any | None = None

@dataclass(kw_only=True)
class PropertyStub(Any):
    owner: Class
    propertyName: str
    resolvedProperty: AbstractProperty | None = None

@dataclass(kw_only=True)
class EnumStub(Any):
    enumeration: Enumeration
    enumName: str
    resolvedEnum: Enum | None = None

@dataclass(kw_only=True)
class Association(PropertyOwner):
    properties: list[Property] = field(default_factory=list)
    originalMilestonedProperties: list[Property] = field(default_factory=list)
    qualifiedProperties: list[QualifiedProperty] = field(default_factory=list)

@dataclass(kw_only=True)
class Profile(PackageableElement):
    p_stereotypes: list[Stereotype] = field(default_factory=list)
    p_tags: list[Tag] = field(default_factory=list)

@dataclass(kw_only=True)
class Annotation(Any):
    profile: Profile
    value: str
    modelElements: list[AnnotatedElement] = field(default_factory=list)

@dataclass(kw_only=True)
class Stereotype(Annotation):
    pass

@dataclass(kw_only=True)
class Tag(Annotation):
    pass

@dataclass(kw_only=True)
class TaggedValue(Any):
    tag: Tag
    value: str

@dataclass(kw_only=True)
class KeyExpression(Any):
    key: InstanceValue
    expression: ValueSpecification
    add: bool | None = None

@dataclass(kw_only=True)
class ClassProjection(Class, PackageableElement):
    projectionSpecification: RootRouteNode

@dataclass(kw_only=True)
class AssociationProjection(Association):
    projectedAssociation: Association
    projections: list[ClassProjection] = field(default_factory=list)

@dataclass(kw_only=True)
class RouteNode(AnnotatedElement):
    name: str
    includeAll: str
    type: GenericType
    children: list[PropertyRouteNode] = field(default_factory=list)
    resolvedProperties: list[AbstractProperty] = field(default_factory=list)
    included: list[RouteNodePropertyStub] = field(default_factory=list)
    excluded: list[RouteNodePropertyStub] = field(default_factory=list)

@dataclass(kw_only=True)
class RootRouteNode(RouteNode):
    owner: Any | None = None

@dataclass(kw_only=True)
class PropertyRouteNode(RouteNode):
    propertyName: str
    root: RootRouteNode

@dataclass(kw_only=True)
class ExistingPropertyRouteNode(PropertyRouteNode):
    property: RouteNodePropertyStub

@dataclass(kw_only=True)
class NewPropertyRouteNode(PropertyRouteNode):
    specifications: list[ValueSpecification] = field(default_factory=list)
    functionDefinition: NewPropertyRouteNodeFunctionDefinition

@dataclass(kw_only=True)
class RouteNodePropertyStub(AnnotatedElement):
    property: list[AbstractProperty] = field(default_factory=list)
    owner: RouteNode
    parameters: list[InstanceValue] = field(default_factory=list)

@dataclass(kw_only=True)
class NewPropertyRouteNodeFunctionDefinition(FunctionDefinition):
    owner: NewPropertyRouteNode

@dataclass(kw_only=True)
class Constraint(Any):
    name: str
    owner: str | None = None
    externalId: str | None = None
    functionDefinition: FunctionDefinition
    enforcementLevel: str | None = None
    messageFunction: FunctionDefinition | None = None

@dataclass(kw_only=True)
class GrammarInfoStub(Any):
    value: Any
    original: Any

@dataclass(kw_only=True)
class DefaultValue(Any):
    functionDefinition: FunctionDefinition | None = None

@dataclass(kw_only=True)
class Test(Any):
    id: str
    testable: Testable

@dataclass(kw_only=True)
class GenericTypeOperation(GenericType):
    left: GenericType
    right: GenericType
    type: GenericTypeOperationType

@dataclass(kw_only=True)
class RelationType(Type, Referenceable):
    columns: list[Column] = field(default_factory=list)

@dataclass(kw_only=True)
class Relation(Any):
    pass

@dataclass(kw_only=True)
class RelationElementAccessor(Relation, Referenceable):
    sourceElementContainer: PackageableElement | None = None
    sourceElement: Any

@dataclass(kw_only=True)
class Column(Function, AnnotatedElement):
    nameWildCard: bool

# --- Primitive types -----------------------------------------------------
String = PrimitiveType(name="String")
Boolean = PrimitiveType(name="Boolean")
Byte = PrimitiveType(name="Byte")
Number = PrimitiveType(name="Number")
Integer = PrimitiveType(name="Integer")
StrictTime = PrimitiveType(name="StrictTime")
Date = PrimitiveType(name="Date")
StrictDate = PrimitiveType(name="StrictDate")
DateTime = PrimitiveType(name="DateTime")
LatestDate = PrimitiveType(name="LatestDate")
Float = PrimitiveType(name="Float")
Decimal = PrimitiveType(name="Decimal")

# --- Packageable multiplicities ------------------------------------------
ZeroOne = PackageableMultiplicity(name="ZeroOne", lowerBound=MultiplicityValue(value=0), upperBound=MultiplicityValue(value=1))
PureOne = PackageableMultiplicity(name="PureOne", lowerBound=MultiplicityValue(value=1), upperBound=MultiplicityValue(value=1))
PureZero = PackageableMultiplicity(name="PureZero", lowerBound=MultiplicityValue(value=0), upperBound=MultiplicityValue(value=0))
ZeroMany = PackageableMultiplicity(name="ZeroMany", lowerBound=MultiplicityValue(value=0))
OneMany = PackageableMultiplicity(name="OneMany", lowerBound=MultiplicityValue(value=1))

__all__ = [
    "AggregationKind",
    "GenericTypeOperationType",
    "Class",
    "TypeParameter",
    "GenericType",
    "InferredGenericType",
    "PackageableElement",
    "Referenceable",
    "ReferenceUsage",
    "PropertyOwner",
    "ElementWithStereotypes",
    "ElementWithTaggedValues",
    "ElementWithConstraints",
    "AnnotatedElement",
    "ModelElement",
    "Type",
    "DataType",
    "Measure",
    "PrimitiveType",
    "Unit",
    "Enumeration",
    "Enum",
    "Nil",
    "Any",
    "ElementOverride",
    "GetterOverride",
    "ConstraintsOverride",
    "ConstraintsGetterOverride",
    "Multiplicity",
    "MultiplicityValue",
    "PackageableMultiplicity",
    "Generalization",
    "Property",
    "Package",
    "ImportGroup",
    "Import",
    "ValueSpecification",
    "Expression",
    "NonExecutableValueSpecification",
    "VariableExpression",
    "InstanceValue",
    "ValueSpecificationContext",
    "ExpressionSequenceValueSpecificationContext",
    "InstanceValueSpecificationContext",
    "ClassConstraintValueSpecificationContext",
    "ParameterValueSpecificationContext",
    "KeyValueValueSpecificationContext",
    "FunctionExpression",
    "SimpleFunctionExpression",
    "Function",
    "PackageableFunction",
    "FunctionDefinition",
    "NativeFunction",
    "FunctionType",
    "AbstractProperty",
    "QualifiedProperty",
    "ConcreteFunctionDefinition",
    "LambdaFunction",
    "ImportStub",
    "PropertyStub",
    "EnumStub",
    "Association",
    "Profile",
    "Annotation",
    "Stereotype",
    "Tag",
    "TaggedValue",
    "KeyExpression",
    "ClassProjection",
    "AssociationProjection",
    "RouteNode",
    "RootRouteNode",
    "PropertyRouteNode",
    "ExistingPropertyRouteNode",
    "NewPropertyRouteNode",
    "RouteNodePropertyStub",
    "NewPropertyRouteNodeFunctionDefinition",
    "Constraint",
    "GrammarInfoStub",
    "DefaultValue",
    "Test",
    "Testable",
    "GenericTypeOperation",
    "RelationType",
    "Relation",
    "RelationElementAccessor",
    "Column",
    "String",
    "Boolean",
    "Byte",
    "Number",
    "Integer",
    "StrictTime",
    "Date",
    "StrictDate",
    "DateTime",
    "LatestDate",
    "Float",
    "Decimal",
    "ZeroOne",
    "PureOne",
    "PureZero",
    "ZeroMany",
    "OneMany",
]
