"""Generate a PCT (Pure Compatibility Test) compatibility report.

This is the inverse-side companion to Legend's own ``GeneratePCT``: it reads the
PCT data Legend ships as JSON (vendored under ``vendor/legend-pure/pct/``) and
renders a Markdown matrix of Pure functions with a single **pure-python** column
showing how many of each function's tests pass.

Two kinds of vendored file feed it (one pair per *group* -- essential, grammar,
standard, relation, unclassified, variant):

* ``FUNCTIONS_<group>.json`` -- the function definitions (the report's rows).
* ``ADAPTER_<group>_compiled_Native.json`` -- the per-function test results for
  Legend's **compiled** execution adapter.

The pure-python column reflects that compiled-execution adapter -- the same
engine path :meth:`pure_python.legend.bridge.LegendBridge.evaluate` delegates to
-- so it shows pure-python's execution-oracle coverage of the function library.
The data is a pinned snapshot (see ``vendor/legend-pure/SOURCE.txt``); no JVM is
needed to render the report.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from pathlib import Path

_PCT_DIR = Path(__file__).resolve().parents[2] / "vendor" / "legend-pure" / "pct"
_GROUPS = ("essential", "grammar", "standard", "relation", "unclassified", "variant")


@dataclass
class FunctionRow:
    group: str
    name: str
    source_id: str
    declared_tests: int  # testCount from the function definition (0 if unknown)
    passed: int = 0
    total: int = 0
    failures: list[tuple[str, str | None]] = field(default_factory=list)  # (testName, errorMessage)

    @property
    def cell(self) -> str:
        if self.total == 0:
            return "&empty;"  # no PCT tests for this function
        return f"{self.passed}/{self.total}"


@dataclass
class Report:
    rows: list[FunctionRow]

    def by_group(self) -> dict[str, list[FunctionRow]]:
        out: dict[str, list[FunctionRow]] = {g: [] for g in _GROUPS}
        for row in self.rows:
            out.setdefault(row.group, []).append(row)
        return {g: rows for g, rows in out.items() if rows}

    def totals(self) -> tuple[int, int]:
        return sum(r.passed for r in self.rows), sum(r.total for r in self.rows)


def _name_from_source(source_id: str) -> str:
    leaf = source_id.rsplit("/", 1)[-1]
    return leaf[:-5] if leaf.endswith(".pure") else leaf


def load_report(pct_dir: Path = _PCT_DIR) -> Report:
    """Join the vendored function definitions and compiled-adapter results."""
    rows: dict[str, FunctionRow] = {}

    for group in _GROUPS:
        functions_file = pct_dir / f"FUNCTIONS_{group}.json"
        if not functions_file.is_file():
            continue
        data = json.loads(functions_file.read_text(encoding="utf-8"))
        for fn in data.get("functionDefinitions", []):
            source_id = fn["sourceId"]
            rows[source_id] = FunctionRow(
                group=group,
                name=fn.get("name") or _name_from_source(source_id),
                source_id=source_id,
                declared_tests=fn.get("pctTestCount") or fn.get("testCount") or 0,
            )

    for group in _GROUPS:
        adapter_file = pct_dir / f"ADAPTER_{group}_compiled_Native.json"
        if not adapter_file.is_file():
            continue
        data = json.loads(adapter_file.read_text(encoding="utf-8"))
        for function_test in data.get("functionTests", []):
            source_id = function_test["sourceId"]
            row = rows.get(source_id)
            if row is None:  # results for a source with no declared function (e.g. composition tests)
                row = FunctionRow(group=group, name=_name_from_source(source_id), source_id=source_id, declared_tests=0)
                rows[source_id] = row
            for test in function_test.get("tests", []):
                row.total += 1
                if test.get("success"):
                    row.passed += 1
                else:
                    row.failures.append((test.get("testName", "?"), test.get("errorMessage")))

    ordered = sorted(rows.values(), key=lambda r: (_GROUPS.index(r.group) if r.group in _GROUPS else 99, r.source_id))
    return Report(ordered)


def render_markdown(report: Report) -> str:
    grand_passed, grand_total = report.totals()
    lines: list[str] = [
        "# PCT compatibility report",
        "",
        "Pure Compatibility Test results for the **pure-python** target (Legend "
        "compiled execution -- the engine path `LegendBridge.evaluate` delegates "
        "to). Generated by `python -m pure_python.report.pct` from the pinned PCT "
        "data in `vendor/legend-pure/pct/`. `&empty;` = no PCT tests.",
        "",
        f"**Overall: {grand_passed}/{grand_total} tests passing"
        f"{f' ({100 * grand_passed // grand_total}%)' if grand_total else ''}.**",
        "",
        "| Group | Passed | Total |",
        "| --- | --- | --- |",
    ]
    grouped = report.by_group()
    for group, group_rows in grouped.items():
        gp = sum(r.passed for r in group_rows)
        gt = sum(r.total for r in group_rows)
        lines.append(f"| {group} | {gp} | {gt} |")
    lines.append("")

    failures: list[FunctionRow] = []
    for group, group_rows in grouped.items():
        lines += [f"## {group}", "", "| Function | pure-python |", "| --- | --- |"]
        for row in group_rows:
            lines.append(f"| `{row.name}` | {row.cell} |")
            if row.failures:
                failures.append(row)
        lines.append("")

    if failures:
        lines += ["## Failures", ""]
        for row in failures:
            for test_name, message in row.failures:
                detail = f" — {message.splitlines()[0]}" if message else ""
                lines.append(f"- `{row.name}` / {test_name}{detail}")
        lines.append("")

    return "\n".join(lines)


def generate(out_path: Path, pct_dir: Path = _PCT_DIR) -> Report:
    report = load_report(pct_dir)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_markdown(report), encoding="utf-8")
    return report


def _main() -> None:
    parser = argparse.ArgumentParser(description="Generate the pure-python PCT compatibility report.")
    parser.add_argument("--out", type=Path, default=Path("docs/PCT_Report.md"), help="output Markdown path")
    parser.add_argument("--pct-dir", type=Path, default=_PCT_DIR, help="directory of vendored PCT JSON")
    args = parser.parse_args()

    report = generate(args.out, args.pct_dir)
    passed, total = report.totals()
    pct = f" ({100 * passed // total}%)" if total else ""
    print(f"PCT report: {passed}/{total} tests passing{pct} across {len(report.rows)} functions -> {args.out}")
    for group, rows in report.by_group().items():
        gp = sum(r.passed for r in rows)
        gt = sum(r.total for r in rows)
        print(f"  {group:13} {gp}/{gt}")


if __name__ == "__main__":
    _main()
